" Authors: Mario Ferraz 
" Description: Ma config Perso de VIM 
" Date: 11-07-2021
"------------------------------------------------------------
" Features {{{1
"    ajout de la police pour gvim


set autoindent
set backspace=indent,eol,start
set hidden
set hlsearch
set noshowmode
set noundofile
set autochdir
set noswapfile

" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
if has('filetype')
  filetype indent plugin on
endif


" Enable syntax highlighting
if has('syntax')
  syntax on
endif
" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Enable use of the mouse for all modes
if has('mouse')
  set mouse=a
endif
" Use visual bell instead of beeping when doing something wrong
set visualbell
" Always display the status line, even if only one window is displayed
set laststatus=2
" Better command-line completion
set wildmenu
" Show partial commands in the last line of the screen
set showcmd
" Display line numbers on the left
set number
" pour GVIM 
set guifont=Monospace\ 12

"------------------------------------------------------------
" Indentation options {{{1
"
" Indentation settings according to personal preference.

" Indentation settings for using 4 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=4
set softtabstop=4
set expandtab

"------------------------------------------------------------
" Mappings {{{1
"
" Useful mappings

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>


"------------------------------------------------------------
" Plugin  
"
" Useful mappings
call plug#begin()
Plug 'itchyny/lightline.vim' 
Plug 'frazrepo/vim-rainbow'
Plug 'preservim/NERDTree'
call plug#end()
